import os
import time

os.system("python train.py --config input_config --shot_num 1 --wandb --cat_type cat-t --run_name cyclone_1_t --climatenet_label cyclone")
time.sleep(20)
os.system("python train.py --config input_config  --wandb --cat_type cat-t --run_name cyclone_full_t --climatenet_label cyclone")
time.sleep(20)
os.system("python train.py --config input_config  --wandb --cat_type cat-a --run_name cyclone_full_a --climatenet_label cyclone ")
time.sleep(20)
os.system("python train.py --config input_config --shot_num 1 --wandb --cat_type cat-a --run_name cyclone_1_a --climatenet_label cyclone")
time.sleep(20)
os.system("python train.py --config input_config --shot_num 16 --wandb --cat_type cat-a --run_name river_16_a  --climatenet_label river")
time.sleep(20)
os.system("python train.py --config input_config --shot_num 16 --wandb --cat_type cat-t --run_name river_16_t  --climatenet_label river")
time.sleep(20)
os.system("python train.py --config input_config --shot_num 1 --wandb --cat_type cat-t --run_name river_1_t  --climatenet_label river")
time.sleep(20)
os.system("python train.py --config input_config  --wandb --cat_type cat-t --run_name river_full_t  --climatenet_label river")
time.sleep(20)
os.system("python train.py --config input_config  --wandb --cat_type cat-a --run_name river_full_a  --climatenet_label river")
time.sleep(20)
os.system("python train.py --config input_config --shot_num 1 --wandb --cat_type cat-a --run_name river_1_a --climatenet_label river")
time.sleep(20)
os.system("python train.py --config input_config --shot_num 16 --wandb --cat_type cat-a --run_name cyclone_16_a --climatenet_label cyclone")
time.sleep(20)
os.system("python train.py --config input_config --shot_num 16 --wandb --cat_type cat-t --run_name cyclone_16_t --climatenet_label cyclone")
